# [profile.release]
# panic = 'unwind'

[workspace]
members = [
    'node',
    # 'pallets/template',
    'frame/balances',
    'consensus',
    'consensus/primitives',
    'runtime',
    'runtime/galois',
    'runtime/mathchain',
]
exclude = ["vendor"]
